### ISSUE TITLE
Making devices visible

### ISSUE THREAD

**Issue by jbbarnes77** [jorhett/hubitat-abode#1]
Hi Jo,

I saw the following in the documentation:

> It is possible to identify devices on the Abode and make them
>  visible to Hubitat. I haven't coded this yet because I personally
> didn't need it. Ping me if you feel otherwise.

I would be very interested in that. I have roughly 50 devices on my abode system, and most device types are represented. If Hubitat could read the status of leak and temperature sensors, as well as door open/close status, that would be tremendous. 

Thank you.

**Comment by jorhett** [comment]
The API that Abode gives us would not give you direct visibility into a device state. However, we would receive events when the state transitioned. So for instance, I don't know of a way to determine on request if a door is open or closed. But we receive all events for the Door Open and Door Closed.

In short, even if I build this out I think it will always feel somewhat incomplete due to Abode's inconsistent and undocumented API. But I can likely give you something that works in a limited sense.

If you're okay with knowing that it may never be ideal/perfect, I can try to poke at it this weekend.

**Comment by jbbarnes77** [comment]
I think that would be beneficial in the long run. However, please don't make it any type of priority. The Hubitat is currently unavailable online so I don't have one to test with yet. 

While not ideal, at least knowing about state changes would still be valuable. For instance, I have close to ten abode leak sensors, as well as a Dome water valve. Receiving notification of a leak sensor changing state would be enough to tell the Hubitat it should close the water valve.

**Comment by jbbarnes77** [comment]
BTW, I thought more was possible because I tested out Home Assistant last year and saw the status of all my Abode sensors. I still had that Docker container, so I fired it up last night. 

It did show live status, but the configuration asked for my goabode.com login. So it appears to be getting device status from their cloud instead of locally. What you're saying about the limitations in the API makes sense.

![2020-05-16 17_25_37](https://user-images.githubusercontent.com/35183224/82133581-64325780-979a-11ea-8870-b6d93dd93bba.jpg)

**Comment by raviram203** [comment]
@jbbarnes77 Do you think it would be possible for Hubitat to receive device status from the Abode cloud, in the same manner as Home Assistant?

**Comment by jbbarnes77** [comment]
I wanted to followup to the comment by @raviram203 

My original post was in May as I was only considering Hubitat. I bought one two weeks ago and installed the Abode driver. It is working great.

I also installed a fresh copy of Home Assistant for comparison. Really thorough Abode support. So @raviram203 I believe it would be possible, but recall seeing a post somewhere in which @jorhett said he wasn't happy with Hubitat's stance on security and didn't know that he would be putting much more effort into the Abode code. I do hope that situation turns around, though, as the work he has done is really appreciated.

**Comment by jorhett** [comment]
As I've said previously, something to sync devices between would be something more akin to a HubConnect device for Abode. That would never be part of this project, which has a completely different scope and architecture. There's really no way forward from this to that.

Right now I'm way too busy to consider taking on that work, and don't necessarily have a driving interest in doing it. I encourage someone who has desire and interest to undertake this effort: https://hubconnect.to/knowledgebase
